### ISSUE TITLE
Error on Raspberry Pi

### ISSUE THREAD

**Issue by JacoFourie** [bkeevil/mqtt#28]
Hi. I got a new Raspberry Pi 4 and installed Lazarus 2.0.2 on it. Took ssome time but I got all the packges installed and the IDE rebuild. 

I compile the mqttclient app. 

![image](https://user-images.githubusercontent.com/17771641/62202749-28084480-b38a-11e9-9a50-440efec05149.png)

But as soon as I open it I get this error.

![image](https://user-images.githubusercontent.com/17771641/62202833-52f29880-b38a-11e9-9dd1-9420800329c4.png)

It seems it is coming from the LNet package.

![image](https://user-images.githubusercontent.com/17771641/62202973-964d0700-b38a-11e9-81f8-b852bc6ea67b.png)

**Comment by JacoFourie** [comment]
OK I got it working. Seems there is somthing wrong with the LNet lib. I commented out the SSL error checking and it ran.

![image](https://user-images.githubusercontent.com/17771641/62205191-32790d00-b38f-11e9-9ef7-bd691ea87fca.png)

**Comment by bkeevil** [comment]
I guess I missed this issue. Only the lnet in the online package manager works.
