### ISSUE TITLE
LNet ?

### ISSUE THREAD

**Issue by JacoFourie** [bkeevil/mqtt#8]
Hi.

I am confused. I installed a clean copy of Lazarus 1.8.
I tried to install your components but it is looking for iNet Visual.

Where do I get that?  You state you are using LNet so I am a bit confused at this stage.

Regards.

**Comment by JacoFourie** [comment]
OK when I try to install LNet I get this error

![lnet](https://user-images.githubusercontent.com/17771641/41595235-57a0d090-73c6-11e8-918d-6d2b5ca4f443.JPG)

**Comment by JacoFourie** [comment]
OK I used another version of Lazarus and I managed to compile. But I get a buffer 0 error if I connect to a mosquitto server.

![error](https://user-images.githubusercontent.com/17771641/41595921-df73b396-73c8-11e8-9bdd-42636be959e3.JPG)

**Comment by bkeevil** [comment]
The only version of lnet that works right now is the one available in the online package manager. 

To connect to a default Mosquitto installation you need to set the timeout to less than 60 seconds. 

Not sure about the invalid buffer size. I haven't tested much  on Windows. Can you find out where in the code it is crashing?

**Comment by JacoFourie** [comment]
Hi. What platform and version of Lazarus are you using ?

**Comment by bkeevil** [comment]
Linux Mint 18. Lazarus 1.8.2

**Comment by JacoFourie** [comment]
OK I have it working on Ubuntu. But what I see is that the app will work for about 30 seconds and then the server will close the connection. Not sure why that will be as I am using a broker that a lot of other devices connect to and work with no problem.

**Comment by bkeevil** [comment]
Try setting your timeout value to less than 60 seconds

**Comment by JacoFourie** [comment]
Hi. I set the Keep Alive to 10 seconds. 


![image](https://user-images.githubusercontent.com/17771641/44845838-eab5a700-ac4e-11e8-8eb3-094bb3619124.png)

And it will connect and stay connected. 

![image](https://user-images.githubusercontent.com/17771641/44845810-d1acf600-ac4e-11e8-8dad-e5c83a4bab53.png)

I will subscribe to # just as a test. And it will run for about 10 seconds.

![image](https://user-images.githubusercontent.com/17771641/44845954-3c5e3180-ac4f-11e8-8a60-bcbc948969f6.png)

But then it will show that the server disconnected.

![image](https://user-images.githubusercontent.com/17771641/44846007-644d9500-ac4f-11e8-812f-383925f9545b.png)


But If I do the same using other MQTT tools it stays connected.

![image](https://user-images.githubusercontent.com/17771641/44846197-11281200-ac50-11e8-9c48-536f5b767c1f.png)

![image](https://user-images.githubusercontent.com/17771641/44846279-3d439300-ac50-11e8-9dc5-38cf732f5ec5.png)

**Comment by bkeevil** [comment]
What server?

**Comment by bkeevil** [comment]
Try turning on debug messages with command line parameters to get more detailed logging

**Comment by JacoFourie** [comment]
It is a Mosquitto server. I have been using another MQTT lib for years that works 100%. But it does not support the modes and username / password. If you want you can test against my server as it is open on the internet.

**Comment by JacoFourie** [comment]
This is the lib I have been using 

https://github.com/ZiCog/mqtt-free-pascal

But like what you are doing.

**Comment by bkeevil** [comment]
I can't replicate this bug. I suggest killing your mosquitto server process and running it directly from the command line using the -v option. This will give verbose log output to your console which will help you identify the reason why mosquitto is dropping the connection. Cut and paste the relevant sections of the console output here if you need help.

**Comment by bkeevil** [comment]
In  67afb24 I added a "Show Debug Messages" checkbox to the log tab in the client demo app to make it easier for end users to turn on detailed debug logging.  

You might also want to try checking the "Clean Session" checkbox when you connect.

**Comment by JacoFourie** [comment]
It seems that the ping is not being sent. This is the output I see on the mosquitto side.
all my other MQTT devices send a ping and the server sends a response back,.

1536127494: Received PINGREQ from LoungeLight_F997C2
1536127494: Sending PINGRESP to LoungeLight_F997C2
1536127494: Received PINGREQ from DVES_07A165
1536127494: Sending PINGRESP to DVES_07A165
1536127495: Received PUBLISH from ESP32Client (d0, q0, r0, m0, 'TempLogger/AllValues', ... (223 bytes))
1536127495: Received PINGREQ from OfficeLights_85B425
1536127495: Sending PINGRESP to OfficeLights_85B425
1536127496: Received PINGREQ from ESP32Client
1536127496: Sending PINGRESP to ESP32Client
1536127496: Received PINGREQ from M5Stack_Client


But I don't see that from your demo app and then I see this (JacoFourie is my Client ID on the demo app

1536127389: Client JacoFourie has exceeded timeout, disconnecting.
1536127389: Socket error on client JacoFourie, disconnecting.

**Comment by JacoFourie** [comment]
OK so it seems you stop sending pings as soon as I subscribe to the topic "#"

![image](https://user-images.githubusercontent.com/17771641/45076513-dbb97380-b0ea-11e8-9dde-80c8a1430f81.png)

**Comment by JacoFourie** [comment]
OK not sure yet where the problem is but I just moved the Ping call to the start to bypass your logic as to when to ping and now it works but obviously is is pinging all the time.

```
procedure TMQTTClient.ProcessPingIntervals;
begin
  Ping;
  if FPingIntRemaining = 1 then
    begin
      if FPingCount >= 2 then
        begin
          FPingIntRemaining := 0;
          FPingCount := 0;
          Bail(MQTT_ERROR_NO_PING_RESPONSE);
          Exit;
        end;
      inc(FPingCount);
      FPingIntRemaining := 6;
      Ping;
    end
  else
    if FPingIntRemaining > 1 then
      dec(FPingIntRemaining);
end;                   
````

**Comment by JacoFourie** [comment]
I found it. Your ping thread runs every second. You reset the remaining seconds to wait before you send a ping every time you send or receive data. But is seems that you have to keep on sending pings all the time to the mosquitto broker even if you are sending or receiving data. So I just commented out the 2 spots where you set the counter to the interval where you send and receive data. And I also removed the ping that I moved to the top of the handle ping procedure.

````

procedure TMQTTClient.SendData;
begin
  //FPingIntRemaining := FPingInterval;
  if Assigned(FOnSendData) then
    FOnSendData(Self);
end;

procedure TMQTTClient.DataAvailable;
var
  DestroyPacket: Boolean;
  Packet: TMQTTPacket;
  ErrCode: Word;
begin
  DestroyPacket := True;
  Packet := nil;
  ErrCode := ReadMQTTPacketFromBuffer(FRecvBuffer,Packet,State = csConnected);
  try
    if ErrCode = MQTT_ERROR_NONE then
      begin
        FInsufficientData := 0;
        FPingCount := 0;
        //FPingIntRemaining := FPingInterval;
        if State = csConnected then
          begin
            case Packet.PacketType of
              ptPINGRESP : HandlePINGRESPPacket;
              ptSUBACK   : HandleSUBACKPacket(Packet as TMQTTSUBACKPacket);
              ptUNSUBACK : HandleUNSUBACKPacket(Packet as TMQTTUNSUBACKPacket);
              ptPUBLISH  : HandlePUBLISHPacket(Packet as TMQTTPUBLISHPacket);
              ptPUBACK   : HandlePUBACKPacket(Packet as TMQTTPUBACKPacket);
              ptPUBREC   : HandlePUBRECPacket(Packet as TMQTTPUBRECPacket);
              ptPUBREL   : HandlePUBRELPacket(Packet as TMQTTPUBRELPacket);
              ptPUBCOMP  : HandlePUBCOMPPacket(Packet as TMQTTPUBCOMPPacket);
            else
              Bail(MQTT_ERROR_UNHANDLED_PACKETTYPE);
            end;
            if Packet.PacketType = ptPUBLISH then
              DestroyPacket := (Packet as TMQTTPUBLISHPacket).QOS = qtAT_MOST_ONCE;
          end
        else
          if (State = csDisconnecting) then
            // Ignore any packets while disconnecting
          else
            if (State = csConnecting) and (Packet is TMQTTCONNACKPacket) then
              HandleCONNACKPacket(Packet as TMQTTCONNACKPacket)
            else
              Bail(MQTT_ERROR_NOT_CONNECTED)
      end
    else
      if ErrCode = MQTT_ERROR_INSUFFICIENT_DATA then
        if FInsufficientData >= 2 then
          Bail(ErrCode)
        else
          inc(FInsufficientData)
      else
        Bail(ErrCode);
    // More data?
    if (ErrCode = MQTT_ERROR_NONE) and (FRecvBuffer.Size > 0) then
      DataAvailable;
  finally
    if Assigned(Packet) and DestroyPacket then
      FreeAndNil(Packet);
  end;
end;                   


````

**Comment by JacoFourie** [comment]
The MQTT spec says that if the client does not send any data then it needs to send a ping. 

````
If the broker does not receive a PINGREQ or any other packet from a client, the broker closes the connection and sends the last will and testament message (if the client specified an LWT).
````

In my case I subscribe and get a lot of data and will only send data now and then from the client side. Thus you have to send pings else the sever will close the connection.

https://www.hivemq.com/blog/mqtt-essentials-part-10-alive-client-take-over

So the reset of the ping on the send data can stay but not on the receive data as far as I can tell. I take it you are not seeing this problem as your client is sending data all the time. To get the same issue on the sample client app just connect, subscribe to a topic and leave the client without sending any data and you should see the same problem.

**Comment by bkeevil** [comment]
Not at a computer to check atm. You are running Windows  correct? There have been ongoing issues with finding a timer that works on linux and rpi so I recently replaced the timers with a TThread object that calls a service routine every second. There may be other timers as well, can't remember. I think next we should confirm all timers and the thread are executing in Windows.

**Comment by JacoFourie** [comment]
Hi. No I could not get it working on Windows so I installed it on Ubuntu Linux. If I comment out the one line 

````
//FPingIntRemaining := FPingInterval;
````
on the data receive where you reset the ping interval then all works 100%. Been running for 5 hours now. But if you reset the ping interval on a data receive and you don't send data (or a ping) then the server disconnects you. So there is a logic error as you assume that the client will be sending data as you are resetting the ping counter every time there is data received where in my case I only send now and then as commands but receive telemetry info all the time so then the server will think the client is dead.

**Comment by bkeevil** [comment]
I came to the same conclusion. I've pushed the change directly into master. Please close the issue if it works.

**Comment by JacoFourie** [comment]
Thanks. The app has been running for a day now. So all seems to work now. I will at some stage see if I can get it working on windows and Raspberry Pi

**Comment by bkeevil** [comment]
If you're receiving any QoS1 or 2 packets you'll want to pull yesterday's updates. I plugged a pretty major memory leak.

**Comment by JacoFourie** [comment]
I did thanks. All seems to be working now. When I have time I will play a bit with it. I use MQTT a lot. I use it in this controller https://www.youtube.com/watch?v=AXIwKd8eKqA&t=162s and the Raspberry Pi will send commands with MQTT to all the modules.

**Comment by bkeevil** [comment]
I have the same actuator opening and closing my chicken coop door :-)

**Comment by JacoFourie** [comment]
Is this you ?

https://forum.pololu.com/t/chicken-coop/7333

**Comment by bkeevil** [comment]
No LOL. My chicken coop build is on my YouTube channel but I automated the door afterwards. I should do a video on my home automation projects one of these days.




Sent from my Samsung Galaxy Tab®4


-------- Original message --------
